api_login_check:
    path: /api/login_check

#app_logout:
#    path: /logout
#    methods: GET

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation


app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }